import { BaseMapConfig, GisLayerConfig } from './types';

export const BASE_MAPS: Record<string, BaseMapConfig> = {
  osm: {
    id: 'osm',
    name: 'OpenStreetMap',
    nameHi: 'ओपनस्ट्रीटमैप',
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
    maxZoom: 19,
    previewColor: '#4A90E2',
    description: 'Standard street and topographic reference map',
  },
  satellite: {
    id: 'satellite',
    name: 'Satellite (ESRI)',
    nameHi: 'उपग्रह (सैटेलाइट)',
    attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
    maxZoom: 18,
    previewColor: '#1B4D3E',
    description: 'High-resolution global optical satellite imagery',
    className: 'no-invert-tile',
  },
  terrain: {
    id: 'terrain',
    name: 'Terrain / Topo',
    nameHi: 'धरातल / स्थलाकृतिक',
    attribution: 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ, TomTom, Intermap, iPC, USGS, FAO, NPS, NRCAN, GeoBase, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), and the GIS User Community',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}',
    maxZoom: 18,
    previewColor: '#8C7853',
    description: 'Topographic contour and relief landforms',
    className: 'no-invert-tile',
  },
};

export const GIS_LAYERS: GisLayerConfig[] = [
  // 1. Disaster / Risk Layers
  {
    id: 'flood',
    name: 'Flood Inundation Risk',
    nameHi: 'बाढ़ जलप्लावन जोखिम',
    category: 'disaster',
    description: 'Water accumulation & river overflow inundation zones',
    descriptionHi: 'जल संचय और नदी ओवरफ्लो बाढ़ क्षेत्र',
    defaultActive: true,
    color: '#2563EB',
    sourceUrl: '/data/flood-risk.geojson',
    legend: [
      { label: 'Critical Depth (>2.0m)', labelHi: 'गंभीर स्तर (>2.0m)', color: '#DC2626', type: 'fill' },
      { label: 'High Depth (1.0m - 2.0m)', labelHi: 'उच्च स्तर (1.0-2.0m)', color: '#EA580C', type: 'fill' },
      { label: 'Moderate Depth (0.3m - 1.0m)', labelHi: 'मध्यम स्तर (0.3-1.0m)', color: '#3B82F6', type: 'fill' },
    ],
  },
  {
    id: 'landslide',
    name: 'Landslide Hazard Zones',
    nameHi: 'भूस्खलन संभावित क्षेत्र',
    category: 'disaster',
    description: 'Geotechnical slope instability & debris flow hazard corridors',
    descriptionHi: 'ढलान अस्थिरता एवं भूस्खलन मलबे का मार्ग',
    defaultActive: true,
    color: '#D97706',
    sourceUrl: '/data/landslide-risk.geojson',
    legend: [
      { label: 'Red Alert Slope (>35° Critical)', labelHi: 'रेड अलर्ट ढलान (>35° गंभीर)', color: '#B91C1C', type: 'fill' },
      { label: 'Orange Alert (High Susceptibility)', labelHi: 'ऑरेंज अलर्ट (उच्च संभावना)', color: '#D97706', type: 'fill' },
      { label: 'Yellow Alert (Moderate Slip)', labelHi: 'येलो अलर्ट (मध्यम फिसलन)', color: '#EAB308', type: 'fill' },
    ],
  },
  {
    id: 'rainfall',
    name: 'Precipitation Intensity',
    nameHi: 'वर्षा तीव्रता रडार',
    category: 'disaster',
    description: 'Live rainfall radar bands & simulated meteorological echo',
    descriptionHi: 'लाइव वर्षा रडार एवं मौसम संबंधी अनुमान',
    defaultActive: false,
    color: '#0284C7',
    legend: [
      { label: 'Heavy Torrential (>50 mm/hr)', labelHi: 'अति भारी वर्षा (>50 mm/hr)', color: '#7C3AED', type: 'fill' },
      { label: 'Moderate Rain (15-50 mm/hr)', labelHi: 'मध्यम वर्षा (15-50 mm/hr)', color: '#0284C7', type: 'fill' },
      { label: 'Light Showers (<15 mm/hr)', labelHi: 'हल्की फुहार (<15 mm/hr)', color: '#38BDF8', type: 'fill' },
    ],
  },
  {
    id: 'hazard_zones',
    name: 'Active Hazard Buffer Zones',
    nameHi: 'सक्रिय जोखिम बफर क्षेत्र',
    category: 'disaster',
    description: '1km and 500m protective isolation perimeter around reported hazards',
    descriptionHi: 'दर्ज आपदाओं के चारों ओर सुरक्षा बफर जोन',
    defaultActive: false,
    color: '#EF4444',
    legend: [
      { label: 'Immediate Evacuation Zone (500m)', labelHi: 'तत्काल निकासी क्षेत्र (500m)', color: '#EF4444', type: 'fill', border: '#B91C1C' },
      { label: 'Advisory Caution Perimeter (1km)', labelHi: 'सतर्कता परिधि (1km)', color: '#F97316', type: 'line' },
    ],
  },

  // 2. Infrastructure Layers
  {
    id: 'roads',
    name: 'Evacuation Corridors',
    nameHi: 'निकासी सड़क मार्ग',
    category: 'infrastructure',
    description: 'Primary, secondary, and blocked disaster transit arteries',
    descriptionHi: 'प्राथमिक, द्वितीयक एवं अवरुद्ध आपदा मार्ग',
    defaultActive: true,
    color: '#10B981',
    sourceUrl: '/data/evacuation-roads.geojson',
    legend: [
      { label: 'Clear / Primary Evacuation Route', labelHi: 'खुला / मुख्य निकासी मार्ग', color: '#10B981', type: 'line' },
      { label: 'Caution / Reduced Width Passage', labelHi: 'सावधानी / संकीर्ण मार्ग', color: '#F59E0B', type: 'line' },
      { label: 'Blocked / Hazard Inundated Road', labelHi: 'बंद / अवरुद्ध मार्ग', color: '#EF4444', type: 'line' },
    ],
  },
  {
    id: 'shelters',
    name: 'Emergency Shelters',
    nameHi: 'आपातकालीन राहत शिविर',
    category: 'infrastructure',
    description: 'Designated relief centers, schools, and cyclone shelters',
    descriptionHi: 'निर्दिष्ट राहत केंद्र, विद्यालय एवं सुरक्षा शिविर',
    defaultActive: true,
    color: '#059669',
    legend: [
      { label: 'Operational Shelter (Occupancy < 80%)', labelHi: 'सक्रिय शिविर (क्षमता < 80%)', color: '#059669', type: 'marker' },
      { label: 'Near Capacity Shelter (>80%)', labelHi: 'पूर्ण क्षमता के निकट (>80%)', color: '#D97706', type: 'marker' },
    ],
  },
  {
    id: 'hospitals',
    name: 'Hospitals & Trauma Care',
    nameHi: 'अस्पताल एवं ट्रॉमा सेंटर',
    category: 'infrastructure',
    description: '24/7 emergency medical centers with ICU and blood bank facilities',
    descriptionHi: 'आईसीयू और ब्लड बैंक युक्त 24/7 आपातकालीन अस्पताल',
    defaultActive: true,
    color: '#DC2626',
    legend: [
      { label: 'Trauma & Emergency Hospital (Open 24/7)', labelHi: 'ट्रॉमा अस्पताल (24/7 खुला)', color: '#DC2626', type: 'marker' },
    ],
  },
  {
    id: 'facilities',
    name: 'Emergency Facilities',
    nameHi: 'महत्वपूर्ण आपातकालीन सुविधाएं',
    category: 'infrastructure',
    description: 'Police posts, Fire rescue stations, NDRF camps, and supply depots',
    descriptionHi: 'पुलिस चौकियां, दमकल केंद्र, एनडीआरएफ शिविर',
    defaultActive: false,
    color: '#6366F1',
    sourceUrl: '/data/facilities.geojson',
    legend: [
      { label: 'Fire & Rescue Station', labelHi: 'अग्निशमन केंद्र', color: '#EA580C', type: 'marker' },
      { label: 'Police Control & Transit Station', labelHi: 'पुलिस नियंत्रण कक्ष', color: '#3B82F6', type: 'marker' },
      { label: 'NDRF Disaster Response Camp', labelHi: 'एनडीआरएफ राहत कैंप', color: '#8B5CF6', type: 'marker' },
    ],
  },

  // 3. Geographic Layers
  {
    id: 'admin_boundaries',
    name: 'Administrative Boundaries',
    nameHi: 'प्रशासनिक सीमाएं',
    category: 'geographic',
    description: 'District, Taluk, and Municipal ward demarcation borders',
    descriptionHi: 'जिला, तालुका एवं नगरपालिका वार्ड सीमाएं',
    defaultActive: true,
    color: '#64748B',
    sourceUrl: '/data/administrative-boundaries.geojson',
    legend: [
      { label: 'District Administrative Border', labelHi: 'जिला प्रशासनिक सीमा', color: '#475569', type: 'line' },
      { label: 'Taluk / Sub-District Border', labelHi: 'तालुका / उप-जिला सीमा', color: '#94A3B8', type: 'line' },
    ],
  },
  {
    id: 'rivers',
    name: 'Rivers & Water Bodies',
    nameHi: 'नदियां एवं जल निकाय',
    category: 'geographic',
    description: 'River channels, water reservoirs, drainage basins, and flood plains',
    descriptionHi: 'नदी वाहिकाएं, जलाशय एवं जल निकासी घाटियां',
    defaultActive: true,
    color: '#0EA5E9',
    sourceUrl: '/data/rivers.geojson',
    legend: [
      { label: 'Major River / Flow Channel', labelHi: 'मुख्य नदी वाहिका', color: '#0284C7', type: 'line' },
      { label: 'Reservoir / Lake Waterbody', labelHi: 'जलाशय / झील', color: '#38BDF8', type: 'fill' },
    ],
  },
  {
    id: 'elevation',
    name: 'Elevation & Contours',
    nameHi: 'ऊंचाई एवं समोच्च रेखाएं',
    category: 'geographic',
    description: 'Hypsometric elevation contour lines showing terrain gradient',
    descriptionHi: 'धरातलीय ढलान दर्शाने वाली समोच्च रेखाएं',
    defaultActive: false,
    color: '#84CC16',
    sourceUrl: '/data/elevation-contours.geojson',
    legend: [
      { label: 'High Altitude (>800m ASL)', labelHi: 'उच्च पर्वतीय (>800m)', color: '#854D0E', type: 'line' },
      { label: 'Mid Slope (400m - 800m)', labelHi: 'मध्यम ढलान (400-800m)', color: '#A16207', type: 'line' },
      { label: 'Valley Floor (<400m)', labelHi: 'घाटी तल (<400m)', color: '#65A30D', type: 'line' },
    ],
  },
];
