import { DisasterIncident } from "@/types/disaster";
import { WeatherData } from "@/types/weather";
import { ShelterItem } from "@/types/shelter";

export const MOCK_DISASTER_INCIDENTS: DisasterIncident[] = [
  {
    id: "INC-2026-CYC-01",
    bulletinId: "NDMA/IMD/2026/CYC-DANA-08",
    title: "Severe Cyclonic Storm 'DANA' Coastal Landfall Corridor",
    category: "CYCLONE",
    severity: "CRITICAL",
    alertLevel: "RED",
    issuedBy: "IMD",
    issuanceTime: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    headline: "Red Alert: Coastal Odisha and Gangetic West Bengal under storm surge warning",
    description:
      "Severe Cyclonic storm is centered near lat 20.8°N and long 87.2°E. Sustained wind speeds of 110-120 kmph gusting to 135 kmph expected. Inundation of low-lying areas up to 1.5m above astronomical tide likely.",
    affectedDistricts: ["Kendrapara", "Bhadrak", "Balasore", "Purba Medinipur", "South 24 Parganas"],
    state: "Odisha & West Bengal",
    coordinates: [20.82, 87.21],
    radiusKm: 75,
    evacuationStatus: "MANDATORY",
    safeCorridorRoute: "National Highway 16 Inbound towards Cuttack/Kolkata Elevated Corridor",
    recommendedActions: [
      "Total suspension of fishing operations in North Bay of Bengal",
      "Immediate evacuation from kutcha and semi-pucca dwellings within 5km from coast",
      "Keep battery-powered radios tuned to All India Radio disaster frequencies",
      "Stock 72 hours of boiled drinking water and dry rations",
    ],
    activeHelpline: "1078 (NDRF NDR-KOL)",
  },
  {
    id: "INC-2026-FLD-04",
    bulletinId: "CWC/DEL/FLD-YAMUNA-14",
    title: "River Yamuna Flood Stage Warning (Old Railway Bridge)",
    category: "FLOOD",
    severity: "HIGH",
    alertLevel: "ORANGE",
    issuedBy: "CWC",
    issuanceTime: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    headline: "Water level breached Danger Mark of 205.33m, currently at 206.18m",
    description:
      "Hathnikund barrage discharge sustained at 1.82 lakh cusecs. Floodplains from Wazirabad to Okhla Barrage inundated. SDRF rescue boats deployed across low lying colonies.",
    affectedDistricts: ["East Delhi", "North East Delhi", "Central Delhi"],
    state: "Delhi NCT",
    coordinates: [28.665, 77.242],
    radiusKm: 18,
    evacuationStatus: "ADVISORY",
    safeCorridorRoute: "Ring Road bypass towards Kashmere Gate high ground relief stations",
    recommendedActions: [
      "Move livestock and machinery to elevated embankment areas",
      "Do not attempt wading through submerged underpasses",
      "Report stranded households to Delhi Disaster Control Room at 1077",
    ],
    activeHelpline: "1077 (Delhi SDMA)",
  },
  {
    id: "INC-2026-LND-02",
    bulletinId: "GSI/KL/WND-CHUR-03",
    title: "High Debris Flow Hazard & Landslide Warning",
    category: "LANDSLIDE",
    severity: "HIGH",
    alertLevel: "ORANGE",
    issuedBy: "NDMA",
    issuanceTime: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    headline: "Precipitation threshold exceeded 220mm in 24 hours over Meppadi hills",
    description:
      "Geological Survey of India automated slope inclinometers indicate progressive creep. High risk of debris flow along drainage channels.",
    affectedDistricts: ["Wayanad", "Kozhikode", "Malappuram"],
    state: "Kerala",
    coordinates: [11.554, 76.132],
    radiusKm: 25,
    evacuationStatus: "MANDATORY",
    safeCorridorRoute: "State Highway 59 via Kalpetta designated safe bypass",
    recommendedActions: [
      "Vacate all settlements along hill slopes and riparian margins",
      "Avoid night travel through Western Ghats mountain passes",
    ],
    activeHelpline: "1078 (NDRF 4th Battalion)",
  },
  {
    id: "INC-2026-HWV-07",
    bulletinId: "IMD/NR/HWV-BUL-09",
    title: "Severe Heatwave with Elevated Thermal Comfort Index",
    category: "HEATWAVE",
    severity: "MODERATE",
    alertLevel: "YELLOW",
    issuedBy: "IMD",
    issuanceTime: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    headline: "Maximum temperatures 44.5°C with dry westerly winds across plains",
    description:
      "Heat illness risk moderate for vulnerable populations (infants, elderly, chronic illness). Jal Shakti drinking water booths activated across district transit points.",
    affectedDistricts: ["Jaipur", "Churu", "Bikaner", "Jodhpur"],
    state: "Rajasthan",
    coordinates: [26.9124, 75.7873],
    radiusKm: 120,
    evacuationStatus: "NONE",
    recommendedActions: [
      "Avoid direct sun exposure between 12:00 PM and 3:30 PM",
      "Consume ORS, lassi, lemon water, and coconut water frequently",
    ],
    activeHelpline: "104 (National Health Tele-Advisory)",
  },
];

export const MOCK_SHELTERS: ShelterItem[] = [
  {
    id: "SHL-BAL-01",
    name: "Multi-Purpose Cyclone Shelter, Chandipur Coastal Ward 4",
    type: "CYCLONE_SHELTER",
    coordinates: [21.468, 87.014],
    address: "Near Chandipur High School, Balasore Coastal Block",
    district: "Balasore",
    state: "Odisha",
    totalCapacity: 1200,
    currentOccupancy: 480,
    contactPerson: "Er. Subhashis Mohapatra (Block Development Officer)",
    contactNumber: "+91 94371 82910",
    isOpen: true,
    facilities: ["Solar Generator 25kVA", "Water Purifier (RO)", "Community Kitchen", "Baby Care Zone"],
    medicalOfficerOnDuty: true,
    powerBackup: true,
    drinkingWaterLitres: 14000,
    distanceMeters: 4200,
  },
  {
    id: "SHL-DEL-02",
    name: "Government Senior Model School Flood Relief Camp",
    type: "RELIEF_CAMP",
    coordinates: [28.672, 77.234],
    address: "Bela Road, Kashmere Gate Transit Area",
    district: "Central Delhi",
    state: "Delhi NCT",
    totalCapacity: 850,
    currentOccupancy: 610,
    contactPerson: "Dr. Ananya Sharma (Tehsildar Relief Operations)",
    contactNumber: "+91 98102 44321",
    isOpen: true,
    facilities: ["Dry Rations Supply", "Blankets & Mattresses", "Separate Women Barracks", "Mobile Toilets"],
    medicalOfficerOnDuty: true,
    powerBackup: true,
    drinkingWaterLitres: 9500,
    distanceMeters: 1800,
  },
  {
    id: "SHL-NDRF-08",
    name: "NDRF Regional Rapid Deployment Station - Base Camp 8",
    type: "NDRF_BASE",
    coordinates: [28.535, 77.391],
    address: "Sector 132, Expressway Node, Gautambuddha Nagar Base",
    district: "NCR Sector",
    state: "Delhi/UP",
    totalCapacity: 500,
    currentOccupancy: 120,
    contactPerson: "Commandant R. K. Rawat, NDRF",
    contactNumber: "011-24363260",
    isOpen: true,
    facilities: ["Amphibious Rescue Boats", "Heavy Hydraulic Cutters", "K9 Dog Search Team", "Satellite Uplink"],
    medicalOfficerOnDuty: true,
    powerBackup: true,
    drinkingWaterLitres: 25000,
    distanceMeters: 12400,
  },
  {
    id: "SHL-HOSP-01",
    name: "Dr. Ram Manohar Lohia Hospital Emergency Trauma Ward",
    type: "DISTRICT_HOSPITAL",
    coordinates: [28.625, 77.201],
    address: "Baba Kharak Singh Marg, New Delhi",
    district: "New Delhi",
    state: "Delhi NCT",
    totalCapacity: 450,
    currentOccupancy: 395,
    contactPerson: "Chief Medical Superintendent Office",
    contactNumber: "011-23365525",
    isOpen: true,
    facilities: ["ICU Critical Surge", "Anti-Snake Venom Depot", "Blood Bank Type O-", "Decontamination Unit"],
    medicalOfficerOnDuty: true,
    powerBackup: true,
    drinkingWaterLitres: 40000,
    distanceMeters: 3100,
  },
  {
    id: "SHL-KL-03",
    name: "Meppadi St. Joseph Community Disaster Shelter",
    type: "RELIEF_CAMP",
    coordinates: [11.558, 76.128],
    address: "Opposite Panchayat Bhavan, Meppadi High Range",
    district: "Wayanad",
    state: "Kerala",
    totalCapacity: 600,
    currentOccupancy: 285,
    contactPerson: "Fr. Joseph Varghese / Village Officer",
    contactNumber: "+91 94472 10982",
    isOpen: true,
    facilities: ["Helipad Vicinity Access", "Kitchen & Ready Meals", "Counselling & First Aid", "Satellite Wi-Fi"],
    medicalOfficerOnDuty: true,
    powerBackup: true,
    drinkingWaterLitres: 8000,
    distanceMeters: 2800,
  },
];

export const MOCK_WEATHER_DATA: WeatherData = {
  stationName: "Coastal Surveillance Station 04 - Chandipur",
  state: "Odisha Coast",
  temperatureC: 27.8,
  feelsLikeC: 32.4,
  condition: "Heavy Rain & Squall",
  rainfallPast24hMm: 114.6,
  precipitationProbability: 95,
  windSpeedKmh: 88,
  windGustKmh: 124,
  windDirection: "ENE",
  humidityPercent: 96,
  uvIndex: 1,
  aqiValue: 28,
  aqiCategory: "Good",
  radarStatus: "Operational",
  radarStation: "Paradip Doppler Weather Radar (DWR)",
  imdWarningColor: "Red",
  hourlyForecast: [
    { time: "12 PM", tempC: 28, rainProb: 95, condition: "Heavy Rain" },
    { time: "01 PM", tempC: 27, rainProb: 100, condition: "Squall" },
    { time: "02 PM", tempC: 26, rainProb: 100, condition: "Violent Storm" },
    { time: "03 PM", tempC: 26, rainProb: 90, condition: "Heavy Rain" },
    { time: "04 PM", tempC: 27, rainProb: 80, condition: "Showers" },
    { time: "05 PM", tempC: 27, rainProb: 75, condition: "Showers" },
  ],
};
